<?php

switch ($lng) {
	case "en":
		$inst_welcome = "Welcome in NoteSys";
		$inst_instruct = "Setup config.php and then push this button.";
		$do_install = "Install NoteSys";
		$installed = "NoteSys was installed. Delete folder install.";
		$discard = "Back to web (discard changes)";
		$goback = "Back to web";
		$submit = "Submit";
		$login = "Login";
		$login_heading = "Login";
		$dologin = "Login";
		$user = "User:";
		$password = "Password:";
		$resetpass = "Password reset";
		$newpass = "New password:";
		$newpass2 = "New password (again):";
		$logout = "Logout";
		$newuser = "New user";
		$rights = "Change rights";
		$delete = "Delete";
		$edit = "Edit";
		$addnote = "Add note";
		$users = "Users";
		$noetries = "There are no notes in system";
		$editnote = "Edit note";
		$chpass = "Change password";
		$sysconf = "System configuration";
		$title2 = "Title:";
		$heading = "Heading:";
		$textcol = "Text color:";
		$bckgrndcol = "Background color:";
		$dtname = "Date field name:";
		$entryname = "Entry field name:";
		$linkscol = "Links color:";
		$su = "superuser";
		$notes = "Notes";
		$nsver = "Version";
		$exists = "Exists (delete it - security risk)";
		$notexists = "Deleted - OK";
		$instexistch = "Install folder";
		$duplicate = "Username already in use!";
		$rename = "Rename";
		$rp = "Renaming a user will cause reset of his password to blank";
		break;
	case "cz":
		$inst_welcome = "Vítejte v NoteSys";
		$inst_instruct = "Nastavte config.php a pak stiskněte toto tlačítko.";
		$do_install = "Instalovat NoteSys";
		$installed = "NoteSys byl nainstalován. Smažte adresář install.";
		$discard = "Zpátky na web (zrušit změny)";
		$goback = "Zpátky na web";
		$submit = "Odeslat";
		$login = "Přihlásit";
		$login_heading = "Přihlášení";
		$dologin = "Přihlásit";
		$user = "Uživatel:";
		$password = "Heslo:";
		$resetpass = "Reset hesla";
		$newpass = "Nové heslo:";
		$newpass2 = "Nové heslo (potvrzení):";
		$logout = "Odhlásit";
		$newuser = "Nový uživatel";
		$rights = "Změnit práva";
		$delete = "Smazat";
		$edit = "Upravit";
		$addnote = "Přidat poznámku";
		$users = "Uživatelé";
		$noetries = "V systému nejsou žádné poznámky";
		$editnote = "Upravit poznámku";
		$chpass = "Změna hesla";
		$sysconf = "Nastavení systému";
		$title2 = "Titulek:";
		$heading = "Nadpis:";
		$textcol = "Barva textu:";
		$bckgrndcol = "Barva pozadí:";
		$dtname = "Popisek pole pro datum:";
		$entryname = "Popisek pole pro zápis:";
		$linkscol = "Barva odkazů:";
		$su = "superuživatel";
		$notes = "Poznámky";
		$nsver = "Verze";
		$exists = "Existuje (smažte - bezpečnostní riziko)";
		$notexists = "Smazána - OK";
		$instexistch = "Instalační složka";
		$duplicate = "Jméno již použito!";
		$rename = "Přejmenovat";
		$rp = "Přejmenování uživatele způsobí reset jeho hesla na prázdné";
		break;
}
?>